#file used for checking code coverage

name: Run tests and upload coverage

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        env:
          GEODB_X_RAPID_API_KEY: ${{ secrets.GEODB_X_RAPID_API_KEY }}
          GEODB_X_RAPID_API_HOST: ${{ secrets.GEODB_X_RAPID_API_HOST }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET_KEY: ${{ secrets.AMADEUS_API_SECRET_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          FOURSQUARE_API_KEY: ${{ secrets.FOURSQUARE_API_KEY }}
          WEATHER_BIT_X_RAPID_API_KEY: ${{ secrets.WEATHER_BIT_X_RAPID_API_KEY }}
          WEATHER_BIT_X_RAPID_API_HOST: ${{ secrets.WEATHER_BIT_X_RAPID_API_HOST }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          PYTHONPATH: ${{ github.workspace }} 
          DJANGO_SETTINGS_MODULE: CityByte.settings
        run: pytest $PYTHONPATH/CityByte/tests/tests_api.py --cov --cov-report=xml

      - name: Upload Results to Codecov
        uses: codecov/codecov-action@v4
        with:
          # files: ./coverage.xml
          # flags: unittests
          # name: codecov-coverage
          token: 21de6785-688f-4521-bf50-6b60a0f79636
